# Используем официальный образ с Node.js
FROM node:20
LABEL author="gbaka <geo.m2019@mail.ru>"

# Директория для сервиса внутри контейнера
WORKDIR /app

# Копируем файл с зависимостями
COPY . .

# # Устанавливаем зависимости (описаны в package.json)
RUN npm install 

# # Собираем проект с помощью Vite
RUN npm run build

# Dev-сервер фронтенда работает на 3030 порту
EXPOSE 3030

# Запускаем сервер, чтобы обслуживать статику
CMD ["npm", "run", "dev"]
