services:
  database:
    build: ./database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=forecast_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=forecast_db
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend


volumes:
  postgres_data:
