services:
  database:
    image: ghcr.io/gbaka/predictify-database:develop
    build: ./database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend-dev:
    image: ghcr.io/gbaka/predictify-backend:develop
    build:
      context: ./backend
      dockerfile: Dockerfile.dev  
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./backend:/app  
    depends_on:
      - database

  scheduler-dev:
    image: ghcr.io/gbaka/predictify-scheduler:develop
    build: 
      context: .
      dockerfile: scheduler/Dockerfile.dev
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./scheduler:/app/scheduler
      - ./backend/services:/app/services
      - ./backend/database:/app/database
      - ./backend/logger.py:/app/logger.py
    depends_on:
      - database

  frontend-dev:
    image: ghcr.io/gbaka/predictify-frontend:develop
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3030:3030"
    volumes:
      - ./frontend:/app 
      - /app/node_modules
    depends_on:
      - backend-dev  


volumes:
  postgres_data:
