services:
  database:
    build: ./database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=forecast_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev  
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app  

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3030:3030"
    volumes:
      - ./frontend:/app 
      - /app/node_modules           


volumes:
  postgres_data:
