services:
  database:
    image: ghcr.io/gbaka/predictify-database:latest
    build: ./database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    image: ghcr.io/gbaka/predictify-backend:latest
    build: ./backend
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    depends_on:
      - database
    restart: unless-stopped

  scheduler:
    image: ghcr.io/gbaka/predictify-scheduler:latest
    build: 
      context: .
      dockerfile: scheduler/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    depends_on:
      - database
    restart: unless-stopped

  frontend:
    image: ghcr.io/gbaka/predictify-frontend:latest
    build: ./frontend
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - backend
    restart: unless-stopped


volumes:
  postgres_data:
