services:
  database:
    build: ./database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=forecast_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev  
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=forecast_db
    volumes:
      - ./backend:/app  

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3030:3030"
    volumes:
      - ./frontend:/app 
      - /app/node_modules           


volumes:
  postgres_data:
