services:
  database:
    image: ghcr.io/gbaka/predictify-database:latest
    build: ./database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=forecast_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: ghcr.io/gbaka/predictify-backend:latest
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=forecast_db
    depends_on:
      - database

  scheduler:
    image: ghcr.io/gbaka/predictify-scheduler:latest
    build: 
      context: .
      dockerfile: scheduler/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=forecast_db
    depends_on:
      - database

  frontend:
    image: ghcr.io/gbaka/predictify-frontend:latest
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend


volumes:
  postgres_data:
