# Используем бзовый образ Python 3.12
FROM python:3.12-slim
LABEL author="gbaka <geo.m2019@mail.ru>"

# Директория для сервиса внутри контейнера
WORKDIR /app

# Копируем файл с зависимостями
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install -r requirements.txt

# Dev-сервер бэкэнда работает на 8000 порту
EXPOSE 8000

# Запускаем FastAPI с Uvicorn (дебаг-конфигурация)
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--log-level", "critical"]
