# Используем бзовый образ Python 3.12
FROM python:3.12-slim
LABEL author="gbaka <geo.m2019@mail.ru>"

# Для данного Dockerfile директорией сборки является корневая директория проекта!


# Директория для сервиса внутри контейнера
WORKDIR /app/scheduler

# Копируем файл с зависимостями
COPY scheduler/requirements.txt .

# Устанавливаем зависимости
RUN pip install -r requirements.txt

WORKDIR /app

# Запускаем планировщик
CMD ["python", "./scheduler/main.py"]

