# Конфиг-файл планировщика
# database -> tablename должны соответствовать моделям из backend/database/models.py (+crud объекты из backend/database/crud.py, +backend/routes.py)
# - name должны соответствовать именам из маппинг таблицы baseMappingTable компонента frontend/src/components/ForecastTiles/ForecastTiles.jsx

tasks:
  - name: "temperature_forecast"
    parser:
      type: "OpenMeteo"
      params:
        latitude: 55.7558
        longitude: 37.6176
        hourly: "temperature_2m"
        start_date: !py3 "(datetime.now() - timedelta(days=3)).strftime('%Y-%m-%d')"
        end_date: !py3 "(datetime.now() - timedelta(days=2)).strftime('%Y-%m-%d')"
    model:
      type: "SARIMA"
      observation_window_size: 200
      params:
        p: 2
        d: 2
        q: 1 
        P: 2
        D: 1
        Q: 1
        s: 24
        steps: 24
        trend: "t"
        significance_level: 0.05
        enforce_stationarity: true
        enforce_invertibility: true
    database:
      tablename: "temperature_forecast"
    schedule:
      pooling_interval: 900  # в секундах
      retry_cooldown: 300

  - name: "relative_humidity_forecast"
    parser:
      type: "OpenMeteo"
      params:
        latitude: 55.7558
        longitude: 37.6176
        hourly: "relative_humidity_2m"
        start_date: !py3 "(datetime.now() - timedelta(days=3)).strftime('%Y-%m-%d')"
        end_date: !py3 "(datetime.now() - timedelta(days=2)).strftime('%Y-%m-%d')"
    model:
      type: "SARIMA"
      observation_window_size: 200
      params:
        p: 2
        d: 2
        q: 2 
        P: 0
        D: 2
        Q: 2
        s: 24
        steps: 24
        trend: "t"
        significance_level: 0.05
        enforce_stationarity: true
        enforce_invertibility: true
    database:
      tablename: "relative_humidity_forecast"
    schedule:
      pooling_interval: 900  # в секундах
      retry_cooldown: 300

  - name: "wind_speed_forecast"
    parser:
      type: "OpenMeteo"
      params:
        latitude: 55.7558
        longitude: 37.6176
        hourly: "wind_speed_10m"
        start_date: !py3 "(datetime.now() - timedelta(days=3)).strftime('%Y-%m-%d')"
        end_date: !py3 "(datetime.now() - timedelta(days=2)).strftime('%Y-%m-%d')"
    model:
      type: "SARIMA"
      observation_window_size: 200
      params:
        p: 1
        d: 2
        q: 2 
        P: 1
        D: 1
        Q: 1
        s: 24
        steps: 24
        trend: "t"
        significance_level: 0.05
        enforce_stationarity: true
        enforce_invertibility: true
    database:
      tablename: "wind_speed_forecast"
    schedule:
      pooling_interval: 900  # в секундах
      retry_cooldown: 300

  - name: "precipitation_forecast"
    parser:
      type: "OpenMeteo"
      params:
        latitude: 55.7558
        longitude: 37.6176
        hourly: "precipitation"
        start_date: !py3 "(datetime.now() - timedelta(days=5)).strftime('%Y-%m-%d')"
        end_date: !py3 "(datetime.now() - timedelta(days=2)).strftime('%Y-%m-%d')"
    model:
      type: "ARIMA"
      observation_window_size: 200
      params:
        p: 0
        d: 0
        q: 1
        steps: 24
        trend: "c"
        significance_level: 0.05
        enforce_stationarity: true
        enforce_invertibility: true
    database:
      tablename: "precipitation_forecast"
    schedule:
      pooling_interval: 900  # в секундах
      retry_cooldown: 300
  