name: CI/CD Deploy to VPS

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/predictify-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/predictify-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Build & Push Scheduler
        uses: docker/build-push-action@v5
        with:
          context: .
          file: scheduler/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/predictify-scheduler:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Build & Push Database
        uses: docker/build-push-action@v5
        with:
          context: ./database
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/predictify-database:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
  deploy:
    needs: build-and-push
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      
      - name: Remove old docker-compose.yml on VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            rm -f /home/${{ secrets.VPS_USER }}/project/docker-compose.yml

      - name: Copy docker-compose.yml to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.VPS_USER }}/project/"

      - name: Create .env file on VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            cat <<_EOF_ > /home/${{ secrets.VPS_USER }}/project/.env
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_HOST=database
            DB_PORT=5432
            DB_NAME=forecast_db
            _EOF_

      - name: Log in to GHCR on VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
    
      - name: Deploy on VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            cd /home/${{ secrets.VPS_USER }}/project
            docker compose down
            docker compose pull
            docker compose up -d
