name: CI Develop

on:
  push:
    branches: 
     - develop

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: backend/Dockerfile.dev
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/predictify-backend:develop
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: frontend/Dockerfile.dev
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/predictify-frontend:develop
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & Push Scheduler
        uses: docker/build-push-action@v5
        with:
          context: .
          file: scheduler/Dockerfile.dev
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/predictify-scheduler:develop
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & Push Database
        uses: docker/build-push-action@v5
        with:
          context: ./database
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/predictify-database:develop
          cache-from: type=gha
          cache-to: type=gha,mode=max